### ISSUE TITLE
Block by ip+account name instead of only ip

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/security#27]
As we talked about in https://github.com/owncloud/core/issues/1580, it seems that ip+account name combination is the best option to block. In addition to this, (#26) the whitelist enhancement prevents users or companies blocking their own networks. @PVince81, @phil-davis Do you have something to add?

**Comment by ownclouders** [comment]
It seems you've just enabled the issue triaging. I'm just scraping all issues from your repository and will give you some more information about this in a few minutes or so.

Because of the rate limit we can't scrape all information (including all comments and authors) right now - our system is already set up to scrape this in the next days over which the predictions will become more precise every day.

**Sit tight!**

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the label prediction failed because there are not enough labels. Three labels must have been set on at least three issues each.

The contributor prediction failed because there are not enough contributors. Three contributors must have authored comments on at least three issues each.

**Comment by phil-davis** [comment]
I agree - you don;t want easy denial-of-service from people blocking out access from particular IP addresses that tend to have a lot of real users NATed behind them. Blocking each IP+account combination that trips the password failure rules, plus a whitelist seems to give a balance between blocking brute-force attacks vs avoiding denial of service.

**Comment by DeepDiver1975** [comment]
fixes with #29
